name: Build/Test

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e pep8

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e py3

  build:
    name: Build the charm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: latest/stable
      - name: Build charm(s)
        id: builder
        run: |
          sudo snap install charmcraft --classic
          charmcraft pack -v
          ./rename.sh
      - name: Upload built charm
        uses: actions/upload-artifact@v3
        with:
          name: charms
          path: "*.charm"

  functional-test:
    needs:
      - lint
      - unit-test
      - build
    name: Functional test
    runs-on: [self-hosted, xlarge]
    steps:

      - name: Download charm
        uses: actions/download-artifact@v3
        with:
          name: charms
          path: ~/artifacts/

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install sunbeam
        run: |
          date
          sudo snap install openstack --channel 2023.2
          sunbeam prepare-node-script | bash -x
          sg snap_daemon "sunbeam cluster bootstrap --accept-defaults"
          sg snap_daemon "sunbeam cluster list"
          juju status -m admin/controller
          juju status -m openstack
          date

      - name: Get actionutils
        run: |
          curl -sL https://raw.githubusercontent.com/canonical/microceph/main/tests/scripts/actionutils.sh -o ~/actionutils.sh
          chmod +x ~/actionutils.sh

      - name: Upgrade to locally built charm
        run: |
          juju refresh microceph --path ~/artifacts/microceph.charm
          juju add-unit -m admin/controller microceph --to 0
          # Wait for unit to show up
          for i in $( seq 1 20 ) ; do
              if juju status -m admin/controller | grep -E 'microceph/.*active.*idle' ; then
                  echo "microceph unit active"; break
              else
                  echo -n "." ; sleep 4
              fi
          done
          sudo snap list
          juju status -m admin/controller
          # TODO: We can't upgrade the snap via the charm yet, do it by hand
          sudo snap refresh microceph --channel=reef/edge

      - name: Add disks
        run: |
          set -eux
          juju run microceph/0 add-osd loop-spec=4G,3
          sudo microceph.ceph -s
          ~/actionutils.sh wait_for_osds 3
          sudo microceph.ceph -s

  juju-test:
    needs:
      - lint
      - unit-test
      - build
    name: Juju test
    runs-on: [self-hosted, xlarge]
    steps:

      - name: Download charm
        uses: actions/download-artifact@v3
        with:
          name: charms
          path: ~/artifacts/

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1

      - name: Install dependencies
        run: |
          date
          sudo snap install juju
          mkdir -p ~/.local/share/juju
          juju bootstrap localhost
          juju add-model microceph-test
          date

      - name: Install MicroCeph charm
        run: |
          date
          juju deploy -n 3 ~/artifacts/microceph.charm
          juju wait-for application microceph --query='name=="microceph" && (status=="active" || status=="idle")'
          date

      - name: Show Juju status
        run: |
          set -eux
          juju status

      - name: Add disks
        run: |
          set -eux
          juju run microceph/0 add-osd loop-spec=4G,1 --wait=2m
          juju run microceph/1 add-osd loop-spec=4G,1 --wait=2m
          juju run microceph/2 add-osd loop-spec=4G,1 --wait=2m

      - name: Remove Unit
        run: |
          set -x
          juju remove-unit microceph/2 --no-prompt
          # wait and check if the unit is still present.
          for i in $(seq 1 8); do
            res=$( ( juju status | grep -cF "microceph/2" ) || true )
            if [[ $res -gt 0 ]] ; then
              echo -n '.'
              sleep 5
            else
              echo "Unit removed successfully"
              break
            fi
          done
          # fail if unit still present.
          if [[ $res -gt 0 ]] ; then
            echo "Unit still present"
            juju status
            exit 1
          fi
          juju exec --unit microceph/0 -- microceph status
